# Generated by Django 3.1.5 on 2021-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='title',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
