# Generated by Django 3.1.5 on 2021-02-05 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='user',
            new_name='user_auction',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='user_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='watchlist',
            field=models.ManyToManyField(related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
