# Generated by Django 3.1.5 on 2021-01-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210129_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListings',
            new_name='AuctionListing',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
