# Generated by Django 3.1.5 on 2021-01-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210129_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('1', 'Fashions'), ('2', 'Toys'), ('3', 'Electronics'), ('4', 'Home')], default=1, max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
