# Generated by Django 3.1.5 on 2021-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210205_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='active_bid',
            field=models.BooleanField(default=True),
        ),
    ]
