# Generated by Django 3.1.5 on 2021-01-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210130_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='image',
            new_name='imageURL',
        ),
    ]
