# Generated by Django 3.1.5 on 2021-02-06 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_active_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user_bid',
            field=models.ForeignKey(default='No one', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
